[package]
name = "rex-lexer"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
