[package]
name = "rex-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.87" }
thiserror = "1.0"
