[package]
name = "rex-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
rex-ast = { path = "../rex-ast" }
thiserror = { workspace = true }
