[package]
name = "rex-parser"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
regex = { workspace = true }
rex-ast = { workspace = true }
rex-lexer = { workspace = true }
thiserror = { workspace = true }
