[package]
name = "rex-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
rex-ast = { path = "../rex-ast" }
rex-lexer = { path = "../rex-lexer" }
rpds = { version = "1.1" }
thiserror = { version = "1.0" }
