[package]
name = "rex-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]
