[package]
name = "rex"
version = "0.1.0"
edition = "2021"

[dependencies]
rex-ast = { path = "../rex-ast" }
rex-engine = { path = "../rex-engine" }
rex-object = { path = "../rex-object" }
rex-macros = { path = "../rex-macros" }
rex-parser = { path = "../rex-parser" }
rex-resolver = { path = "../rex-resolver" }
