[book]
title = "Rex"
authors = ["Rex contributors"]
language = "en"
src = "src"
description = "Rex (short for Rush Expressions) is a strongly-typed functional DSL for defining workflows."

[build]
build-dir = "book"

[preprocessor.rexlang-wasm]
command = "cargo run --manifest-path ../Cargo.toml -p rexlang-mdbook --"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/talo/rex"
edit-url-template = "https://github.com/talo/rex/edit/v4/docs/{path}"
site-url = "/rex/"
additional-js = ["disable_help_shortcut.js"]

[output.html.playground]
editable = false
copyable = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true

[output.html.fold]
enable = true
level = 1
