[package]
name = "rex-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
rex-ast = { path = "../rex-ast" }
rex-parser = { path = "../rex-parser" }
rex-resolver = { path = "../rex-resolver" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde_json", "dep:serde"]
