[package]
name = "rex-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = { version = "1.1" }
async-trait = { version = "0.1" }
futures = { version = "0.3" }
rex-ast = { path = "../rex-ast" }
rex-lexer = { path = "../rex-lexer" }
rex-parser = { path = "../rex-parser" }
rex-resolver = { path = "../rex-resolver" }
thiserror = { version = "1.0" }
tokio = { version = "1.27.0", features = ["macros", "rt"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[features]
default = ["serde"]
serde = ["dep:serde_json", "dep:serde"]
